// <auto-generated />
using System;
using GrassTesting.Entity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GrassTesting.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GrassTesting.Entity.TravianPlayerHistory", b =>
                {
                    b.Property<int>("Id");

                    b.Property<DateTime>("Date");

                    b.Property<string>("Clan");

                    b.Property<int>("CountPopulation");

                    b.Property<int>("CountVillages");

                    b.Property<string>("Name");

                    b.Property<string>("Nation");

                    b.Property<int>("PointAtt");

                    b.Property<int>("PointDef");

                    b.Property<int>("Rank");

                    b.Property<int>("RankAtt");

                    b.Property<int>("RankDef");

                    b.Property<int>("RankPopulation");

                    b.Property<string>("VillagesJson");

                    b.HasKey("Id", "Date");

                    b.ToTable("TravianPlayersHistory");
                });

            modelBuilder.Entity("GrassTesting.Entity.TravianPlayerId", b =>
                {
                    b.Property<int>("Id");

                    b.Property<DateTime?>("DateDeleted");

                    b.HasKey("Id");

                    b.ToTable("TravianPlayersId");
                });
#pragma warning restore 612, 618
        }
    }
}
